const http = require('http');
const express = require('express');
const app = express();
app.get("/", (request, response) => {
  console.log(Date.now() + " Ping Received");
  response.sendStatus(200);
});
app.listen(process.env.PORT);
setInterval(() => {
  http.get(`http://${process.env.PROJECT_DOMAIN}.glitch.me/`);
}, 280000);
const Discord = require("discord.js");
const client = new Discord.Client();
client.prefix='!';
client.SERVER_ID='301063859702071316';
let RH=require(`./raw.js`);
RH.folder_name=`./modules`; // RH.folder_name='C:/user/discord/bot4/modules';- for pc running
RH.prefix=client.prefix;//prefix for commands; default value: '!'
RH.log=true;//true-console log feedback on;false-console log feedback off; default value:'true'
RH.dm_commands=false; //true - allowed executing commands sending by DM generated by RH event handler; false - this commands not allowed; default value:false;
RH.fetch_members=false;
RH.fetch_messages=false;
client.on("raw", (...args) => {try{
     RH.run(client,...args);
}catch(err){console.log(err);}; });

client.login(process.env.TOKEN);
//